[api]
openai_api_key = "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"
firecrawl_api_key = "your-firecrawl-api-key"

[llm]
model = "gpt-4.5-preview"
temperature = 0.7
max_tokens = 4000
timeout = 120

[agent]
default_agent = "manus"  # Options: "manus", "react", "planning", "swe"

[browser]
headless = true
timeout = 30
webdriver = "chrome"  # Options: "chrome", "firefox", "edge", "safari"

[document]
pdf_output_dir = "./output/pdf"
markdown_output_dir = "./output/markdown"
code_output_dir = "./output/code"

[logging]
level = "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
file = "./logs/app.log"
rotation = "1 day"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
